zi0w/HOLO

- next.config.mjs
- package.json
- src/app/honeytips/[id]/page.tsx
- src/app/honeytips/_types/honeytips.type.ts
- src/app/honeytips/_utils/comment.ts
- src/app/honeytips/_utils/post.ts
- src/app/honeytips/page.tsx
- src/app/honeytips/post/_components/PostInput.tsx
- src/app/honeytips/post/page.tsx
- src/app/honeytips/search-results/page.tsx
- src/app/honeytips/update/page.tsx
- src/lib/types/supabase.ts
- yarn.lock
- 꿀팁 게시판  포스트 저장 기능 구현
- 꿀팁 게시판 각 페이지 기본 셋팅 완료
- supabase 연동 포스트 저장 기능 구현 완료
- next.config.mjs: supabase 이미지 url 링크 추가
- supabase Post 테이블 categories 컬럼 추가 후, genTypes 최신 반영 완료
- 2025.01.07
- [O] 화살표 함수로 함수 선언했습니다.
- [O] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [O] 타입 추론이 되는 경우에도 명시적으로 타입 선언했습니다.
> feat: 포스트 저장 기능 구현

- package.json
- src/app/map/_components/KakaoMap.tsx
- src/app/map/_hooks/useKakaoLoader.tsx
- src/app/map/_types/coordinates.ts
- src/app/map/page.tsx
- tsconfig.json
- yarn.lock
- 카카오 지도 API를 이용하여 지도 구현
- useKakaoLoader 훅 코드 작성
- KakaoMap 컴포넌트 코드 작성
- 위도 경도 type 지정 coordinates.ts 파일 생성
- 2025.01.07
> feat: KakaoMap setting

- src/app/honeytips/_components/PostList.tsx
- src/app/honeytips/_components/SearchForm.tsx
- src/app/honeytips/_utils/comment.ts
- src/app/honeytips/_utils/post.ts
- src/app/honeytips/page.tsx
- src/app/honeytips/post/_components/PostInput.tsx
- 꿀팁 게시판 글목록 페이지 기능 구현
- post 페이지 관련 피드백 수정
- honeytips/SearchForm: 검색창 UI만 일단 구현
- honeytips/PostList: 카테고리별 포스트 데이터 불러오는 기능 구현
- honeytips/PostList: 글 작성하기 버튼 -> 포스트 페이지 링크 연결
- 2025.01.07
> feat: 카테고리별 글목록 fetching 기능 구현

- package.json
- src/app/honeytips/[id]/_components/DetailCard.tsx
- src/app/honeytips/_components/PostList.tsx
- src/app/honeytips/_utils/auth.ts
- src/app/honeytips/_utils/detail.ts
- src/app/honeytips/_utils/post.ts
- src/app/honeytips/post/_components/PostInput.tsx
- src/app/honeytips/update/[id]/_components/UpdatePostCard.tsx
- src/app/honeytips/update/[id]/page.tsx
- src/app/layout.tsx
- yarn.lock
- 꿀팁 게시판 디테일 페이지 기능 구현
- package.json: swiper 라이브러리 설치
- app/layout: swiper css import
- honetips/utils: detail supabase 로직
- honeytips/[id]: 게시글 디테일 페이지 기능 구현
- honeytips/update/[id]: 디테일 페이지에서 -> 수정 페이지 동적 라우팅 연결
- 2025.01.07
> feat: 디테일 페이지 기능 구현

- src/app/map/_components/KakaoMap.tsx
- src/app/map/_hooks/useCategoriesSearch.ts
- src/app/map/_hooks/useKakaoLoader.ts
- src/app/map/_hooks/useKakaoMap.ts
- 지도 카테고리 마커 표시 및 리스트 구현
- useCategoriesSearch 훅 파일을 생성하여 카테고리 기능 구현
- 2025.01.08
> feat: 카테고리 클릭 시, 해당 시설 마커 표시 및 리스트 구현

- src/app/honeytips/_actions/update.ts
- src/app/honeytips/_utils/detail.ts
- src/app/honeytips/post/_components/PostInput.tsx
- src/app/honeytips/update/[id]/_components/UpdatePostCard.tsx
- 꿀팁 게시판 포스트 수정/삭제 기능 구현
- honeytips/_actions: 서버 액션 로직 구현
- clsx 로 리팩토링
- 이미지 미리보기 창에 삭제 기능 추가
-2025.01.08
> feat: 포스트 업데이트 기능 구현

- next.config.mjs
- src/app/honeytips/[id]/_components/CommentForm.tsx
- src/app/honeytips/[id]/_components/CommentList.tsx
- src/app/honeytips/[id]/_hooks/useCommentMutaion.ts
- src/app/honeytips/[id]/_hooks/useCommentQuery.ts
- src/app/honeytips/[id]/page.tsx
- src/app/honeytips/_actions/update.ts
- src/app/honeytips/_hooks/useHoneytipsAuth.ts
- src/app/honeytips/_types/honeytips.type.ts
- src/app/honeytips/_utils/comment.ts
- src/app/honeytips/_utils/detail.ts
- src/app/honeytips/_utils/post.ts
- src/app/honeytips/post/page.tsx
- 꿀팁 게시판 디테일 페이지 댓글 기능 구현
- 디테일 페이지 댓글 기능 구현
- 절대경로 수정
- 2025.01.08
> feat: 댓글 CRUD 기능 구현

- src/app/honeytips/_components/PostList.tsx
- src/app/honeytips/_utils/comment.ts
- 꿀팁 게시판 댓글 개수 카운트 기능 구현
- 글 목록 리스트에 하트, 댓글 이모티콘 추가
- 댓글 개수 카운트 기능 구현
- 2025.01.09
> feat: 댓글 개수 카운트 기능 구현

- src/app/honeytips/[id]/_components/CommentList.tsx
- src/app/honeytips/[id]/_components/DetailCard.tsx
- src/app/honeytips/[id]/_components/LikeButton.tsx
- src/app/honeytips/[id]/_hooks/useCommentMutaion.ts
- src/app/honeytips/[id]/_hooks/useCommentQuery.ts
- src/app/honeytips/[id]/_hooks/useLikeMutation.ts
- src/app/honeytips/[id]/_hooks/useLikeQuery.ts
- src/app/honeytips/_components/PostList.tsx
- src/app/honeytips/_utils/like.ts
- 꿀팁 게시판 좋아요 기능 구현
- 좋아요 저장 / 취소 기능 구현
- 낙관적 업데이트 적용
- 좋아요 개수 카운트 기능 구현
- 2025.01.09
> feat: 좋아요 기능 구현

- .eslintrc.json
- src/app/recommend/_actions/fetchDailyFortune.tsx
- src/app/recommend/_actions/fetchRecommendation.ts
- src/app/recommend/fortune/page.tsx
- src/app/recommend/page.tsx
- tsconfig.json
- OpenAI API를 활용한 오늘의 운세 기능 구현
- 오늘의 운세를 요청하는 서버 액션 생성
- 받아온 운세를 recommend/fortune/page.tsx에서 표시
- 2025.01.09
> feat: OpenAI API를 활용한 오늘의 운세 기능 구현

- src/app/honeytips/_actions/update.ts
- src/app/honeytips/post/_components/PostForm.tsx
- src/app/honeytips/update/[id]/_components/UpdatePostCard.tsx
- 꿀팁 게시판 버그 수정
- 글 저장 시, 빈제목, 빈내용으로 저장되는 에러 수정
- 글 수정 시, 유저 아이디 못 받아오는 에러 수정
- 2025.01.09
> fix: PostForm 빈 내용 저장 등 버그 수정

- src/app/honeytips/[id]/_components/CommentCard.tsx
- src/app/honeytips/[id]/_components/CommentForm.tsx
- src/app/honeytips/[id]/_components/CommentList.tsx
- src/app/honeytips/[id]/_components/DetailCard.tsx
- src/app/honeytips/[id]/_components/LikeButton.tsx
- src/app/honeytips/_components/PostCard.tsx
- src/app/honeytips/_components/PostList.tsx
- src/app/honeytips/_utils/like.ts
- src/app/honeytips/_utils/post.ts
- src/components/layout/Header.tsx
- 꿀팁 게시판 코드 리팩토링
- 댓글 리스트/카드 분리
- 포스트 리스트/카드 분리
- Header: 비로그인 시 로직 확인을 위해, 임시적으로 로그아웃 기능 추가해놓음
- 2025.01.10
> refactor: List/Card 코드 분리 및 리팩토링

- src/app/honeytips/[id]/_hooks/useLikeMutation.ts
- src/app/honeytips/_components/PostCard.tsx
- src/app/honeytips/post/page.tsx
- src/app/honeytips/update/[id]/_components/UpdatePostForm.tsx
- src/app/honeytips/update/[id]/page.tsx
- 꿀팁 게시판 코드 정리 및 타입 수정
- useLikeMutation 타입 에러 수정
- css 살짝 변경
- UpdatePostCard => UpdatePostForm 으로 컴포넌트명 변경
- 2025.01.10
> chore: 꿀팁 게시판 코드 정리

- src/app/mypage/[id]/_components/Mylike/LikeCard.tsx
- src/app/mypage/[id]/_components/Mylike/LikeList.tsx
- src/app/mypage/_components/ProfileEditModal.tsx
- src/app/mypage/_components/UserProfile.tsx
- src/app/mypage/_components/mypageform.tsx
- src/app/mypage/_hooks/UseruserInfo.ts
- src/app/mypage/_hooks/useUpdateUserInfo.ts
- src/app/mypage/_utils/Likepost.ts
- src/app/mypage/_utils/user.ts
- src/app/mypage/page.tsx
- src/app/sign-in/_components/GitHubLoginButton.tsx
- src/app/sign-in/_components/GoogleLoginButton.tsx
- src/app/sign-in/_components/KakaoLoginButton.tsx
- src/app/sign-in/_components/Signin.tsx
- src/app/sign-in/_components/SocialLogin.tsx
- src/app/sign-up/_utils/auth.ts
- src/components/layout/Header.tsx
- src/store/authStore.ts
- 소셜로그인 기능 구현
-주스탠드로 상태관리하여 로컬스토리지에 저장
-해당소셜 유저의 소셜 프로필이미지 닉네임 불러오기
- 2025.01.13
- [] 절대 경로로 작성했습니다.
- [] 화살표 함수로 함수 선언했습니다.
> feat:소셜로그인기능구현

- src/app/honeytips/[id]/_components/CommentCard.tsx
- src/app/honeytips/[id]/_components/CommentForm.tsx
- src/app/honeytips/[id]/_components/CommentList.tsx
- src/app/honeytips/[id]/_components/DetailCard.tsx
- src/app/honeytips/[id]/_components/LikeButton.tsx
- src/app/honeytips/[id]/_hooks/useCommentMutaion.ts
- src/app/honeytips/[id]/page.tsx
- src/app/honeytips/_components/PostCard.tsx
- src/app/honeytips/_components/PostList.tsx
- src/app/honeytips/_components/SearchForm.tsx
- src/app/honeytips/_hooks/useHoneytipsAuth.ts
- src/app/honeytips/_utils/auth.ts
- src/app/honeytips/_utils/comment.ts
- src/app/honeytips/_utils/detail.ts
- src/app/honeytips/_utils/like.ts
- src/app/honeytips/_utils/post.ts
- src/app/honeytips/page.tsx
- src/app/honeytips/post/_components/PostForm.tsx
- src/app/honeytips/post/page.tsx
- src/app/honeytips/update/[id]/_components/UpdatePostForm.tsx
- src/app/honeytips/update/[id]/page.tsx
- 꿀팁 게시판 메타 데이터 설정 및 코드 정리
- 코드 리뷰 피드백 반영
- 꿀팁 게시판 각 페이지 메타 데이터 설정
- 시맨틱 태그 활용 코드 정리
- 디자이너님 피드백 반영: 사용자가 선택한 카테고리에서 글쓰기 버튼 클릭시, 글 작성 폼의 카테고리에 해당 카테고리 미리 반영해주기
- 2025.01.13
> chore: 꿀팁 게시판 메타 데이터 설정 및 코드 정리

- src/app/honeytips/[id]/_components/CommentCard.tsx
- src/app/honeytips/[id]/_components/DetailCard.tsx
- src/app/honeytips/[id]/_hooks/useCommentMutaion.ts
- src/app/honeytips/_components/PostCard.tsx
- src/app/honeytips/_components/PostList.tsx
- src/app/honeytips/page.tsx
- 꿀팁게시판 풀리퀘스트 피드백 반영
- 시맨틱 태그 수정
- 메타 데이터 추가 설정
- 에러 메세지 수정
- 2025.01.13
> chore: 꿀팁 게시판 피드백 반영 코드 정리

- src/app/mypage/[id]/_components/Mycomment/CommentCard.tsx
- src/app/mypage/[id]/_components/Mycomment/CommentList.tsx
- src/app/mypage/[id]/_components/Mylike/LikeCard.tsx
- src/app/mypage/[id]/_components/Mylike/LikeList.tsx
- src/app/mypage/[id]/_components/Mypost/PostCard.tsx
- src/app/mypage/[id]/_components/Mypost/PosttList.tsx
- src/app/mypage/[id]/_hooks/MyActivityQueries.ts
- src/app/mypage/[id]/_hooks/MyCommentDataQuery.ts
- src/app/mypage/[id]/_hooks/MyCommentMutations.ts
- src/app/mypage/[id]/_hooks/MyLikeMutation.ts
- src/app/mypage/_components/MyLikeButton.tsx
- src/app/mypage/_components/mypageform.tsx
- src/app/mypage/_utils/MyfetchLikePostsData.ts
- src/app/sign-in/_components/Signin.tsx
- src/app/sign-in/_components/SignoutButton.tsx
- src/app/sign-in/_hooks/useSignout.ts
- 좋아요한 게시글 기능구현완료
-모든 게시글이 출력되는현상 해결
-tanstack query 로 상태관리 로직 작성
- 2025.01.14
> feat:좋아요한 게시글 기능구현완료

- src/app/honeytips/[id]/_components/CommentCard.tsx
- src/app/honeytips/[id]/_components/CommentList.tsx
- src/app/honeytips/[id]/_components/DetailCard.tsx
- src/app/honeytips/[id]/_components/LikeButton.tsx
- src/app/honeytips/[id]/_hooks/useLikeMutation.ts
- src/app/honeytips/_components/BestPostList.tsx
- src/app/honeytips/_components/PostCard.tsx
- src/app/honeytips/_components/PostList.tsx
- src/app/honeytips/_types/honeytips.type.ts
- src/app/honeytips/_utils/comment.ts
- src/app/honeytips/_utils/detail.ts
- src/app/honeytips/_utils/like.ts
- src/app/honeytips/_utils/post.ts
- src/app/hooks/usePagination.tsx
- src/lib/types/supabase.ts
- 꿀팁 게시판 리팩토링
- 좋아요/댓글 개수 불러오는 로직 리팩토링
- 전체 카테고리 추가(디자이너님 피드백)
- 디테일 페이지 좋아요/댓글 개수 추가(디자이너님 피드백)
- 수정/삭제 버튼 드롭다운모달 추가(디자이너님 피드백)
- 2025.01.14
> refactor: 꿀팁 게시판 리팩토링

- src/app/mypage/[id]/_components/Mycomment/MyCommentCard.tsx
- src/app/mypage/[id]/_components/Mycomment/MyCommentList.tsx
- src/app/mypage/[id]/_components/Mylike/LikeList.tsx
- src/app/mypage/[id]/_hooks/MyActivityQueries.ts
- src/app/mypage/[id]/_hooks/MyCommentMutations.ts
- src/app/mypage/_types/CommentWithPost.ts
- src/app/mypage/_utils/MyfetchCommentPostsData.ts
- src/hooks/usePagination.ts
-좋아요 누른 게시물 게시물 출력 기능구현 완료
- tanstack 로직 새로 작성
- - tanstack 로 상태관리
- 2025.01.15
> feat:좋아요 한 게시물 출력 구현완료

- src/app/globals.css
- src/app/honeytips/[id]/_components/CommentCard.tsx
- src/app/honeytips/[id]/_components/CommentForm.tsx
- src/app/honeytips/[id]/_components/CommentList.tsx
- src/app/honeytips/[id]/_components/DetailCard.tsx
- src/app/honeytips/[id]/_components/LikeButton.tsx
- src/app/honeytips/[id]/page.tsx
- src/app/honeytips/_actions/detail.ts
- src/app/honeytips/_components/PostCard.tsx
- src/app/honeytips/_components/PostList.tsx
- src/app/honeytips/_components/SearchForm.tsx
- src/app/honeytips/_constans/post.ts
- src/app/honeytips/page.tsx
- src/app/honeytips/post/_components/PostForm.tsx
- src/app/honeytips/post/_components/SelectModal.tsx
- src/assets/images/honeytips/chevron-down.svg
- src/assets/images/honeytips/plus-circle.svg
- src/components/main/BestPostList.tsx
- 꿀팁 게시판 CSS 변경 작업 등
- 디자인 시안 반영 ui 변경
- 카테고리 셀렉트 -> 드롭모달로 변경
- 사용자가 "전체" 카테고리에서 글작성 버튼 클릭시, 작성 폼 "청소"로 세팅
- 2025.01.16
> chore: 꿀팁 게시판 CSS 변경 등

- src/app/honeytips/[id]/_components/CommentForm.tsx
- src/app/honeytips/[id]/_components/CommentList.tsx
- src/app/honeytips/[id]/_components/DetailCard.tsx
- src/app/honeytips/[id]/_components/LikeButton.tsx
- src/app/honeytips/[id]/page.tsx
- 꿀팁 게시판 좋아요, 댓글 렌더링 동기화 에러 수정
- 댓글 작성 시, 몇 초 후 라고 뜨는 동기화 에러 수정
- 좋아요 렌더링 동기화 에러 수정
- 부모 컴포넌트에서 프롭스로 전체 데이터를 전달 -> 각자 params.id 받아서 수파베이스 함수 호출하는 것으로 변경! 
- 2025.01.16
> fix: 좋아요, 댓글 동기화 에러 수정

- src/app/honeytips/[id]/_components/CommentCard.tsx
- src/app/honeytips/[id]/_components/CommentForm.tsx
- src/app/honeytips/[id]/_components/CommentList.tsx
- src/app/honeytips/[id]/_components/DetailCard.tsx
- src/app/honeytips/[id]/_components/DetailLoading.tsx
- src/app/honeytips/[id]/_components/LikeButton.tsx
- src/app/honeytips/[id]/page.tsx
- src/app/honeytips/_components/PostCardLoading.tsx
- src/app/honeytips/_components/PostList.tsx
- src/components/main/BestPostList.tsx
- 꿀팁 게시판 스켈레톤 로딩 페이지 구현
- 꿀팁 게시판 스켈레톤 로딩 페이지 구현
- 2025.01.17
> feat: 꿀팁 게시판 스켈레톤 로딩 페이지 구현

- src/app/map/_components/CategoryButtons.tsx
- src/app/map/_components/KakaoMap.tsx
- src/app/map/_components/PlaceList.tsx
- src/app/map/_hooks/useCategoriesSearch.ts
- src/app/map/_hooks/useKakaoMap.ts
- src/app/map/_hooks/usePlaceListScrollInView.ts
- src/app/map/_hooks/usePlaceListScrollTo.ts
- src/app/map/_hooks/useScrollIntoViewCategoryBtn.ts
- src/components/main/Map.tsx
- 코드 훅 분리 및 주석달기
- usePlaceListScrollInView 훅 파일에 마커 클릭 시, 리스트에서 해당 장소로 이동 후 표시
- usePlaceListScrollTo 훅 파일은 카테고리 변경 시, 스크롤 최상단으로 이동
- useScrollIntoViewCategoryBtn 훅 파일은 카테고리 버튼 선택 시, 중앙으로 이동
- Map 세그먼트 주석달기
- 2025.01.17
> chore: 코드 훅 분리 및 주석달기

- src/app/map/_hooks/useCategoriesSearch.ts
- chore: 카테고리 초기값 수정
- const [category, setCategory] = useState<string>("맛집") 에서 맛집을 빈 문자열로 수정
- 2025.01.17
> chore: 카테고리 초기값 수정

- src/app/honeytips/[id]/_components/CommentCard.tsx
- src/app/honeytips/[id]/_components/CommentForm.tsx
- src/app/honeytips/[id]/_components/DetailCard.tsx
- src/app/honeytips/_components/DropdownButton.tsx
- src/app/honeytips/post/_components/PostForm.tsx
- src/app/honeytips/post/_components/SelectModal.tsx
- src/components/common/Modal.tsx
- src/components/main/BestPostList.tsx
- src/store/modalStore.ts
- 꿀팁 게시판 알럿 변경 등
- 공통 컴포넌트 모달창 로직 수정
- 꿀팁 게시판 알럿 모달 적용(진행 중)
- 2025.01.17
> chore: 꿀팁 게시판 알럿 변경 등

- src/app/mypage/[id]/_components/Mycomment/MyCommentCard.tsx
- src/app/mypage/[id]/_components/Mycomment/MyCommentList.tsx
- src/app/mypage/[id]/_components/Mylike/MyLikeList.tsx
- src/app/mypage/[id]/_components/Mypost/MyWritingtList.tsx
- src/app/mypage/_components/UserProfile.tsx
- src/app/mypage/_hooks/useUpdateUserInfo.ts
- src/app/mypage/_types/CommentWithPost.ts
- src/app/mypage/_types/MyPostTypes.ts
- src/app/mypage/_utils/MyfetchCommentPostsData.ts
- src/app/mypage/_utils/MyfetchLikePostsData.ts
- src/app/mypage/_utils/MyfetchWritingPostsData.ts
- src/app/mypage/_utils/user.ts
- src/lib/utils/supabase/admin.ts
-무한 랜더링 상황 해결
-무한 랜더링 해결
- 2025.01.17
> feat: 마이페이지 무한렌더링 해결

- src/app/mypage/[id]/_components/Mycomment/MyCommentList.tsx
- src/app/mypage/_types/MyPostTypes.ts
- src/app/mypage/_utils/MyfetchCommentPostsData.ts
- src/app/mypage/_utils/MyfetchLikePostsData.ts
- src/app/mypage/_utils/MyfetchWritingPostsData.ts
- src/hooks/useCheckAuth.ts
- src/store/authStore.ts
- 타입에러 수정
- 타입에러 수정
- 2025.01.17
> fix: 타입에러 수정

- src/app/honeytips/[id]/_components/DetailCard.tsx
- src/app/honeytips/[id]/_components/DetailLoading.tsx
- src/app/honeytips/[id]/_components/LikeButton.tsx
- src/app/honeytips/_components/PostList.tsx
- src/app/honeytips/_utils/comment.ts
- src/app/honeytips/page.tsx
- src/app/honeytips/post/_components/PostForm.tsx
- src/components/common/NavigateBack.tsx
- 꿀팁 게시판 튜터님 피드백 반영
- 주석 처리 로직 삭제
- 뒤로가기 버튼 로직 변경
- 2025.01.17
> chore: 튜터님 피드백 반영 등

- src/app/policy/[id]/_hooks/useFormatPolicyField.tsx
- src/app/policy/_components/PolicyFilter.tsx
- src/app/trash-guide/_components/FoodWasteCheck.tsx
- src/lib/utils/supabase/middleware.ts
- src/middleware.ts
- fix: 빌드 에러 수정
- 사용하지 않는 변수 삭제
- 그외.... 기타등등.....
- 2025.01.17
> fix: 빌드 에러 수정

- src/app/honeytips/[id]/_components/CommentCard.tsx
- src/app/honeytips/[id]/_components/DetailCard.tsx
- src/app/honeytips/_components/PostList.tsx
- src/app/honeytips/post/_components/PostForm.tsx
- src/components/common/NavigateBack.tsx
- src/components/main/BestPostList.tsx
- 꿀팁 게시판 빌드 에러 수정
- 꿀팁 게시판 빌드 에러 수정
- alert 모달로 변경
- 2025.01.17
> chore: 빌드 에러 수정

- src/app/policy/_components/PolicyCont.tsx
- src/components/common/Loading.tsx
- src/middleware.ts
- feat: 로딩 컴포넌트 추가
- 로딩 컴포넌트 추가
- 미들웨어 빌드 에러 수정
- 2025.01.17
> feat: 로딩 컴포넌트 추가

- src/app/sign-in/_hooks/useSignInMutation.ts
-빌드 에러 수정
-빌드 에러 수정 최종
- 2025.01.18
> fix:빌드에러 수정 최종

- src/app/api/policy/[id]/route.ts
- src/app/api/policy/route.ts
- 환경변수 변경
- 제발.....ㅠㅠ
- 2025.01.18
> chore: 환경변수 변경

- src/app/policy/_actions/fetchPolicyList.ts
- src/app/policy/_components/PolicyCont.tsx
- feat: 서버액션으로 바꿈
- 제발...........ㅠㅠ
- 2025.01.18
> feat: 서버액션으로 바꿈

- src/app/api/recommend/route.ts
- src/app/recommend/_components/Result.tsx
- src/components/daily/SaveResultButton.tsx
- src/components/daily/ShareLinkButton.tsx
- src/lib/utils/daily/clipboard.ts
- src/lib/utils/daily/html2canvas.ts
- src/lib/utils/daily/shareLink.ts
- 전반적인 리팩토링 진행
- 결과 공유 링크 생성 기능 유틸함수로 분리 
- 결과 공유 버튼, 결과 저장 버튼 컴포넌트로 분리
- html2canvas, clipboard 유틸함수로 분리
- 2025.01.18
> refactor: 전반적인 리팩토링 진행

- next.config.mjs
- package.json
- src/app/honeytips/[id]/_components/DetailCard.tsx
- src/app/honeytips/[id]/_components/DetailLoading.tsx
- src/app/honeytips/_components/PostCardLoading.tsx
- src/app/honeytips/_utils/auth.ts
- src/app/sign-up/_components/Signup.tsx
- supabase 환경 변수 변경 등
- 꿀팁 게시판 유저 아이디 에러 메시지 삭제
- 튜터님 피드백 반영
- supabse 환경 변수 변경 및 빌드 체크 완료
- 2025.01.19
> chore: supabase 환경 변수 변경 등

- src/components/main/DailyMenu.tsx
- 메인 화면 오늘 메뉴 추천 css 수정
- css 일부 수정
- 2025.01.20
> style: 메인 화면 오늘 메뉴 추천 css 수정

- src/app/map/_components/CategoryButtons.tsx
- src/assets/images/map/cafe.svg
- 지도 타이틀, 카테고리 이미지 배치 수정
- 지도 타이틀 폰트 사이즈 변경
- 카테고리 버튼 이미지 센터로 배치
- 2025.01.20
> style: 지도 타이틀, 카테고리 이미지 배치 수정

- src/app/honeytips/_components/SearchForm.tsx
- 꿀팁 게시판 ui 수정
- 꿀팁 게시판 검색 기능 임시적으로 차단
- 2025.01.20
> chore: 꿀팁 게시판 ui 수정

- src/app/map/_components/MapControls.tsx
- src/store/locationStore.ts
- 현 위치에서 검색 버튼 임시 주석
- onClickReSearch 임시 주석
- 2025.01.20
> chore: 현 위치에서 검색 버튼 임시 주석

- README.md
- readme 작성
- readme 작성
- 나중에 시연 영상 추가할 예정
- 2025.01.20
> chore: readme 작성

- src/app/fortune/_components/Result.tsx
- src/app/layout.tsx
- src/app/recommend/_components/Result.tsx
- src/app/recommend/_layout/Layout.tsx
- src/app/recommend/page.tsx
- src/components/main/DailyMenu.tsx
- css 일부 수정, metaData 일부 수정
- css 수정
- metaData 오타 수정
- 2025.01.20
> chore: css 일부 수정, metaData 일부 수정

- src/app/fortune/_components/Result.tsx
- src/app/honeytips/_components/SearchForm.tsx
- src/app/layout.tsx
- src/app/recommend/_components/Result.tsx
- src/app/recommend/_layout/Layout.tsx
- src/app/recommend/page.tsx
- src/components/main/DailyMenu.tsx
- merge: dev into main
- merge: dev into main
- 2025.01.20
> merge: dev into main

- src/app/recommend/page.tsx
- src/components/main/DailyMenu.tsx
- css 일부 수정
- css 일부 수정
- 2025.01.20
> style: css 일부 수정

- src/app/honeytips/[id]/_components/CommentCard.tsx
- src/app/honeytips/[id]/_components/DetailCard.tsx
- src/app/honeytips/[id]/_components/LikeButton.tsx
- src/app/honeytips/_components/PostCard.tsx
- src/app/honeytips/_components/PostList.tsx
- src/app/honeytips/_components/SortButton.tsx
- src/app/honeytips/_utils/formatDate.ts
- src/app/honeytips/_utils/like.ts
- src/components/main/BestPostList.tsx
- 꿀팁 게시판 정렬 기능 구현
- 꿀팁 게시판 최신순/인기순 정렬 기능 추가
- 비로그인 상태에서 좋아요 버튼 클릭 시, "로그인이 필요합니다." 알럿 기능 추가
- 작성일자 "몇 초 후"로 뜨는 에러 수정 => formatDate() util 함수로 로직 분리
- 2025.01.21
> feat: 꿀팁 게시판 정렬 기능 구현

- src/app/honeytips/_components/PostList.tsx
- src/app/honeytips/_components/SearchForm.tsx
- src/app/honeytips/page.tsx
- src/app/honeytips/post/_components/SelectModal.tsx
- src/app/honeytips/search-results/page.tsx
- 꿀팁 게시판 검색 기능 구현
- 꿀팁 게시판 검색 기능 구현
- 작성 폼 셀렉트 붕괴되는 거 수정
- 2025.01.22
> feat: 꿀팁 게시판 검색 기능 구현

- src/app/honeytips/page.tsx
- src/lib/utils/supabase/middleware.ts
- src/middleware.ts
- 미들웨어 redirect 구현
- 비로그인 시, 마이페이지/포스트 작성 페이지 접근 제한 => 로그인으로 리다이렉트
- 로그인 시, 로그인/회원가입 접근 제한 => 메인으로 리다이렉트
- 2025.01.22
> feat: 미들웨어 redirect 구현

- src/app/globals.css
- src/app/honeytips/[id]/_components/DetailCard.tsx
- src/app/honeytips/[id]/_components/ShareButton.tsx
- src/app/honeytips/_components/PostList.tsx
- src/app/mypage/[id]/_components/my-comment/_utils/comments.ts
- src/app/mypage/[id]/_components/my-comment/hooks/useComments.ts
- src/app/mypage/[id]/_components/mylike/_hooks/useMyLikes.ts
- src/app/mypage/[id]/_components/mylike/_utils/likes.ts
- src/app/mypage/_types/like.ts
- src/app/mypage/_types/useMyTypes.ts
- src/assets/images/honeytips/shareIcon.svg
- 꿀팁게시판 swiper ui 수정 등
- 꿀팁게시판 swiper ui 수정
- 디테일 페이지 공유버튼 추가
- 마이페이지 빌드 타입에러 수정
- 2025.01.22
> chore: 꿀팁게시판 swiper ui 수정 등

- src/app/honeytips/[id]/_components/CommentCard.tsx
- src/app/honeytips/[id]/_components/LikeButton.tsx
- src/app/honeytips/_components/PostList.tsx
- src/app/honeytips/post/_components/PostForm.tsx
- src/components/common/LoginModal.tsx
- src/store/loginModalStore.ts
- 꿀팁 게시판 댓글 작성자 뱃지 추가 등
- 꿀팁 게시판 댓글 작성자 뱃지 추가 등
- 알럿 => 모달로 변경 (버그 확인 요망)
- 로그인 유도 알럿 => 모달로 변경 (이 로직은 괜찮은 거 같음)
- 2025.01.23
> feat: 댓글 작성자 뱃지 추가

- src/app/honeytips/[id]/_components/CommentCard.tsx
- src/app/honeytips/[id]/_components/CommentList.tsx
- src/app/honeytips/[id]/_hooks/useToggle.ts
- src/app/honeytips/post/_components/PostForm.tsx
- 꿀팁게시판 CommentCard 리팩토링
- 꿀팁게시판 CommentCard 상태관리 로직 삭제(류제천 튜터님 피드백)
- 부모컴포넌트 CommentList에서 관리하고 Props로 전부 내려줌
- PostForm ui 수정
- 2025.01.27
> refactor: 꿀팁게시판 CommentCard 리팩토링

- src/app/honeytips/[id]/_components/CommentCard.tsx
- src/app/honeytips/[id]/_components/DetailCard.tsx
- src/app/honeytips/_utils/post.ts
- supabase 이미지 용량 최적화
- supabase 이미지 용량 최적화 로직 추가
- 2025.01.31
> refactor: supabase 이미지 용량 최적화

- src/app/honeytips/_components/PostList.tsx
- src/app/honeytips/_components/SortButton.tsx
- 최신순/인기순 디폴트값 변경
- 꿀팁 게시판 최신순/인기순 디폴트값 변경
- 2025.01.31
> chore: 최신순/인기순 디폴트값 변경

- src/app/map/_components/CategoryButtons.tsx
- src/app/map/_components/KakaoMap.tsx
- src/app/map/_components/PlaceList.tsx
- src/app/map/_hooks/useCategoriesSearch.ts
- src/components/main/Map.tsx
- 동네 핫플 페이지 리스트 UI 수정
- 웹 화면에서 마커를 선택하면 해당 마커로 줌 확대
- 클릭 시, 장소 표시 리스트 UI 수정
- 2025.01.31
> style: 동네 핫플 페이지 리스트 UI 수정

- src/app/mypage/[id]/_components/my-comment/MyCommentCard.tsx
- src/app/mypage/[id]/_components/my-comment/MyCommentList.tsx
- src/app/mypage/[id]/_components/mylike/LikeCard.tsx
- src/app/mypage/[id]/_components/mylike/LikeList.tsx
- src/app/mypage/[id]/_components/mypost/WritingCard.tsx
- src/app/mypage/[id]/_components/mypost/WritingList.tsx
- src/app/mypage/_components/DeleteAccount.tsx
- src/app/mypage/_components/DeleteModal.tsx
- src/app/mypage/_components/ImageNicknameForm.tsx
- src/app/mypage/_components/MypageForm.tsx
- src/app/mypage/_components/PasswordChangeModal.tsx
- src/app/mypage/_components/ProfileModal.tsx
- src/app/mypage/_components/RemoveModal.tsx
- src/app/mypage/_components/UserProfile.tsx
- src/app/sign-in/_components/CustomLogoutModal.tsx
- src/app/sign-in/_components/Signin.tsx
- src/app/sign-in/_components/SigninModal.tsx
- src/app/sign-in/_components/SignoutButton.tsx
- src/app/sign-in/_components/SocialLogin.tsx
- src/app/sign-up/_components/SignUpModal.tsx
- src/app/sign-up/_components/Signup.tsx
- src/components/layout/HeaderAuthLink.tsx
- src/store/signoutmodal/useSignoutModalStore.ts
- 커스텀값으로 적용된부분 프리셋에 맞게 수정
- 커스텀값으로 적용된부분 프리셋에 맞게 수정
- 로그아웃 커스텀 모달 1개로 통일
- 빌드 환경에서 에러 확인 완료
- 2025.02.02
> style: 커스텀값으로 적용된부분 프리셋에 맞게 수정

- src/app/globals.css
- src/components/common/MainHeader.tsx
- src/components/layout/Header.tsx
- src/components/layout/HeaderAuthLink.tsx
- src/components/main/PolicyAndTrashBanner.tsx
- style: 메인 배너 슬라이드 화살표, 로고, 네비 스타일 변경
- 메인 배너 슬라이드 화살표 스타일 변경 
- 로고 스타일 변경(이미지 경고 해결)
- 네비에서 active된 링크 스타일 변경
- 2025.02.03
> style: 메인 배너 슬라이드 화살표, 로고, 네비 스타일 변경

- src/app/fortune/_components/Result.tsx
- src/components/main/MainBanner.tsx
- chore: 오타 수정
- 포츈 -> 포춘으로 수정
- 2025.02.03
> chore: 오타 수정

- src/app/honeytips/[id]/_components/CommentCard.tsx
- src/app/honeytips/[id]/_components/CommentForm.tsx
- src/app/honeytips/[id]/_components/DetailCard.tsx
- src/app/honeytips/[id]/_components/LikeButton.tsx
- src/app/honeytips/[id]/_components/ShareButton.tsx
- src/app/honeytips/_components/DropdownButton.tsx
- src/app/honeytips/_components/PostList.tsx
- src/app/honeytips/_components/SearchForm.tsx
- src/app/honeytips/_components/SortButton.tsx
- src/app/honeytips/post/_components/PostForm.tsx
- src/app/honeytips/post/_components/SelectModal.tsx
- src/components/common/Pagination.tsx
- 꿀팁게시판 접근성 보완
- 꿀팁게시판 접근성 보완(버튼 aria-label 지정)
- 2025.02.03
> chore: 꿀팁게시판 접근성 보완

- src/app/api/delete-user/route.ts
- src/app/mypage/[id]/_components/my-comment/MyCommentList.tsx
- src/app/mypage/[id]/_components/my-comment/hooks/useComments.ts
- src/app/mypage/[id]/_components/mylike/LikeCard.tsx
- src/app/mypage/[id]/_components/mylike/LikeList.tsx
- src/app/mypage/[id]/_components/mylike/_utils/formatDate.ts
- src/app/mypage/[id]/_components/mylike/_utils/likes.ts
- src/app/mypage/[id]/_components/mypost/WritingList.tsx
- src/app/mypage/[id]/_components/mypost/_hooks/useMyWriting.ts
- src/app/mypage/[id]/_components/mypost/_utils/posts.ts
- src/app/mypage/_components/ImageNicknameForm.tsx
- src/app/mypage/_components/MypageForm.tsx
- src/app/mypage/_components/UserProfile.tsx
- src/app/mypage/_hooks/useProfileChangeHooks.ts
- src/app/mypage/_utils/myImageUtils.ts
- src/app/sign-in/_components/SignoutButton.tsx
- chore: 안쓰는 로직및 주석삭제
- chore: 안쓰는 로직및 주석삭제
- 빌드환경에서 에러확인 
- 프로필 이미지 최적화
- 2025.02.04
> chore: 안쓰는 로직및 주석삭제

- next.config.mjs
- src/app/globals.css
- src/app/policy/[id]/_components/PolicyDetailItem.tsx
- src/app/policy/[id]/_hooks/useFormatPolicyField.ts
- src/app/policy/page.tsx
- src/app/trash-guide/_components/FoodWasteCheck.tsx
- src/app/trash-guide/_components/TrashLayoutBox.tsx
- src/components/common/NavigateBack.tsx
- refactor: 최적화작업 , chore: next.config수정
- 최적화작업
- next.config수정
- 파일명 수정
- 2025.02.04
> refactor: 최적화작업 , chore: next.config수정

- src/components/common/BestPostLoading.tsx
- src/components/main/BestPostList.tsx
- 로딩페이지 스켈레톤 ui 추가
- 홈화면 꿀팁 로딩페이지 스켈레톤 ui 추가
- 2025.02.04
> style: 로딩페이지 스켈레톤 ui 추가

- next.config.mjs
- package.json
- yarn.lock
- refactor: tenser-webpack-plugin 적용 + chore: sharp 설치
- 성능 최적화를 위한 tenser-webpack-plugin 적용
- 이미지 최적화를 위한 sharp 설치
- 2025.02.04
> refactor: tenser-webpack-plugin 적용 + chore: sharp 설치

- src/app/mypage/_components/UserProfile.tsx
- style: 마이페이지 텍스트 위치변경
-  마이페이지 텍스트 위치변경
- 빌드환경에서 에러확인 완료
- 2025.02.05
> style: 마이페이지 텍스트 위치변경

- src/app/globals.css
- src/app/policy/_components/PolicyCont.tsx
- src/app/policy/_utils/policyApi.ts
- feat: 청년 정책 페이지 타입추가 및 isr로 변경
- 타입추가
- isr로 변경
- 2025.02.05
> feat: 청년 정책 페이지 타입추가 및 isr로 변경

- src/app/honeytips/[id]/_components/CommentCard.tsx
- src/app/honeytips/[id]/_components/CommentList.tsx
- src/app/honeytips/[id]/_components/DetailCard.tsx
- src/app/honeytips/_components/PostCard.tsx
- src/app/honeytips/_components/PostList.tsx
- image 태그 및 ui 수정
- 이미지 태그 priority 속성 추가
- 이미지 사이즈 변경
- p 태그 => li 태그로 변경
- 2025.02.05
> chore: image 태그 및 ui 수정

- src/app/mypage/_components/ContentSkeleton.tsx
- src/app/mypage/_components/MypageForm.tsx
- src/app/mypage/_components/ProfileSkeleton.tsx
- 마이페이지 스켈레톤UI 적용
- style: 마이페이지 스켈레톤UI 적용
- 2025.02.05
> style: 마이페이지 스켈레톤UI 적용

- src/app/mypage/[id]/_components/my-comment/MyCommentList.tsx
- src/app/mypage/[id]/_components/mylike/LikeList.tsx
- src/app/mypage/[id]/_components/mypost/WritingList.tsx
- src/app/mypage/_components/UserProfile.tsx
- 마이페이지 : 스피너 로딩 스타일 변경
- 마이페이지 : 스피너 로딩 스타일 변경
- 2025.02.05
> style: 마이페이지 - 스피너 로딩 스타일 변경

- src/app/mypage/_components/MypageForm.tsx
- src/app/policy/_components/PolicyCont.tsx
- src/app/policy/_components/PolicyFilter.tsx
- src/app/policy/page.tsx
- feat: 청년 정책 맛보기...👓
- feat: 청년 정책 맛보기...👓
- 마이페이지 padding-top 지우기
- 2025.02.05
> feat: 청년 정책 맛보기...👓

- src/app/honeytips/[id]/_components/CommentCard.tsx
- src/app/honeytips/[id]/_components/DetailCard.tsx
- src/app/honeytips/_components/PostCard.tsx
- 꿀팁 게시판 image 태그 css 수정
- image 가로세로 비율 문제 해결
- 2025.02.05
> style: image 태그 css 수정

- src/app/mypage/[id]/_components/my-comment/MyCommentCard.tsx
- src/app/mypage/[id]/_components/mylike/LikeCard.tsx
- src/app/mypage/[id]/_components/mypost/WritingCard.tsx
- src/app/sign-in/_hooks/useSignout.ts
- src/app/sign-in/actions/signout.ts
- 로그아웃 서버액션으로 기능변경
- 로그아웃 서버액션으로 기능변경
- 게시물 사진없을때 디폴트이미지 추가 
- 빌드 환경에서 에러 확인
- 2025.02.05
> feat: 로그아웃 서버액션으로 기능변경

- src/app/map/_components/CategorySkeleton.tsx
- src/app/map/_components/KakaoMap.tsx
- src/app/map/_components/MapContainer.tsx
- src/app/map/_components/SkeletonMap.tsx
- src/app/map/_hooks/useCategoriesSearch.ts
- src/components/main/Map.tsx
- 배포 환경에서 초기 접속, 새로고침 시 마커 찍히지 않는 문제 해결
- 배포 환경에서 초기 접속과 새로고침 시 마커 찍히지 않는 문제 해결
- 핫플 페이지 새로고침, 초기 접속 시, 내 위치가 찍혀있지 않는 문제 해결
- 핫플 페이지 스켈레톤UI 수정 적용
- 2025.02.06
> chore: 배포 환경에서 초기 접속, 새로고침 시 마커 찍히지 않는 문제 해결

- src/app/mypage/[id]/_components/mylike/LikeCard.tsx
- src/app/mypage/[id]/_components/mypost/WritingCard.tsx
- style: 게시글 프로필이미지 스타일 통일
- style: 게시글 프로필이미지 스타일 통일
- 2025.02.06
> style: 게시글 프로필이미지 스타일 통일
